### ISSUE TITLE
Entries not pushed to Pocket

### ISSUE THREAD

**Issue by giokeyboard** [FraGag/feeds-to-pocket#8]
Since a couple of days ago, the entries synced by the app are not pushed to my Pocket account.
Here are some steps I tried in order to see if the issue was temporary:

- I have tested both versions v0.1.6 and v.0.1.7 (the latter compiled manually as it wasn't uploaded to crates.io) both locally and from a remote instance (where the app has always worked flawlessly)
- I also tried to force update the app and its dependencies (everything was fine in the process)
- I called the API endpoint manually `https://getpocket.com/v3/add` with few test entries passing `consumer_key`, `access_token` as per my YAML file. In all cases I got a 200 response and the entries got uploaded successfully to my Pocket. This seems to exclude any authentication or authorization issue from my end.

The app seems to work as I can see the logs 'downloading feeds' and 'pushing feeds to Pocket', but they don't get uploaded to my Pocket as they always did.

If anybody is experiencing the same issue or can help, please let me know!

**Comment by FraGag** [comment]
This issue started occurring for me too on 2024-09-25. The last successful push was at 18:08:24 (UTC-4) on that day, but the next push at 20:10:22 and all subsequent pushes appear to succeed, but don't appear on Pocket. I don't remember updating any software on my computer during that 2-hour window (I usually do updates on Saturdays and this was a Wednesday) and I didn't reboot my computer in that window either, but I did perform updates and reboots since and the problem persists.

I've tried pushing something using the Pocket button in Firefox and that worked. I also tried running the `login` command again but that just returned the same access token. (If I revoked the app's access in my account settings, then perhaps it'd return a different access token, but I haven't tried that yet, and I'm not sure it would change anything.)

I find it intriguing that calling the API manually works. This suggests that there's something in the HTTP request that the app builds that causes an issue. When I have some time (hopefully next weekend), I'll look into this and also at the HTTP response (maybe it's trying to tell us something and we're ignoring it!).

**Comment by FraGag** [comment]
So, many things went wrong for this to happen:

1. The `X_ERROR_CODE` constant had the wrong value (fixed in ca7c67314545148319393d59038c9d1491e8a065). This mistake was introduced in 0dd2dab649941026d4b4c25adf42142cdf3e46cb.
2. Error detection was based solely on the presence of the `X-Error-Code` header, rather than on the HTTP status code. I added code in 338f9b7a825a5e028a67da4b60d9c4a7901ec585 to report an error if we receive an HTTP 4xx or 5xx error, even if the `X-Error-Code` header is missing.
3. Finally, I fixed the actual reason that pushes failed, which is that the API server now apparently rejects `null` for the `title` field (fixed in ef9f2919c8d90df32442acf585ce4d00d980aee2). The field is still optional, so the fix was to omit the field in the request. Currently, feeds-to-pocket never sets the `title` field.
